In [2]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

In [3]:
sess = tf.Session()

## tf.reshape

In [4]:
t = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
# tensor 't' has shape [9]

result = tf.reshape(t, [3, 3])
sess.run(result)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [5]:
t = tf.constant([[[1, 1], [2, 2]],
                 [[3, 3], [4, 4]]])
# tensor 't' has shape [2, 2, 2]
result = tf.reshape(t, [2, 4])
sess.run(result)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]], dtype=int32)

In [6]:
t = tf.constant([[[1, 1, 1],
                   [2, 2, 2]],
                  [[3, 3, 3],
                   [4, 4, 4]],
                  [[5, 5, 5],
                   [6, 6, 6]]])
# tensor 't' has shape [3, 2, 3]
# pass '[-1]' to flatten 't'
result = tf.reshape(t, [-1])
sess.run(result)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6], dtype=int32)

In [7]:
# -1 can also be used to infer the shape

# -1 is inferred to be 9:
result = tf.reshape(t, [2, -1])
sess.run(result)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]], dtype=int32)

In [8]:
# -1 is inferred to be 2:
result = tf.reshape(t, [-1, 9])
sess.run(result)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]], dtype=int32)

In [9]:
# -1 is inferred to be 3:
result = tf.reshape(t, [ 2, -1, 3])
sess.run(result)

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]], dtype=int32)

In [10]:
t = tf.constant([7])
# shape `[]` reshapes to a scalar
result = tf.reshape(t, [])
sess.run(result)

7

## tf.expand_dims

In [11]:
t = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
expanded_1 = tf.expand_dims(t, axis=0)
sess.run((expanded_1, tf.shape(t), tf.shape(expanded_1)))

(array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32),
 array([9], dtype=int32),
 array([1, 9], dtype=int32))

In [12]:
expanded_2 = expanded_1[:, :, tf.newaxis]
sess.run((expanded_2, tf.shape(expanded_2)))

(array([[[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]], dtype=int32),
 array([1, 9, 1], dtype=int32))