In [25]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

In [26]:
sess = tf.Session()

In [27]:
# Both a and b are order 2; (3,2), (2,3)
a = tf.constant([[1, 2, 3], 
                 [-1, -2, -3]])
b = tf.constant([[1, 1],
                 [0, 1],
                 [10, 10]])
c = tf.tensordot(a, b, axes=1) # matrix multiplication; equivalent to axes=[[1], [0]]; the first 1 axis of a and the last 1 axis of b
result = sess.run(c)
result

array([[ 31,  33],
       [-31, -33]], dtype=int32)

In [28]:
d = tf.tensordot(a, b, axes=0) # outer product
sess.run(d)

array([[[[  1,   1],
         [  0,   1],
         [ 10,  10]],

        [[  2,   2],
         [  0,   2],
         [ 20,  20]],

        [[  3,   3],
         [  0,   3],
         [ 30,  30]]],


       [[[ -1,  -1],
         [  0,  -1],
         [-10, -10]],

        [[ -2,  -2],
         [  0,  -2],
         [-20, -20]],

        [[ -3,  -3],
         [  0,  -3],
         [-30, -30]]]], dtype=int32)

In [29]:
# Both a and b are order 2; (3,2), (2,3)
a = tf.constant([[1, 2, 3], 
                 [-1, -2, -3]])
b = tf.constant([[1, 2],
                 [3, 5],
                 [7, 11]])
d1 = tf.tensordot(a, b, axes=2) # equivalent to axes=[[0,1], [0,1]]
d2 = tf.tensordot(a, b, axes=[[0,1], [0,1]]) # (1,2,3)*(1,2,3) + (-1,-2,-3)*(5,7,11)
d3 = tf.tensordot(a, b, axes=[[1,0], [0,1]])
d4 = tf.tensordot(a, b, axes=[[1,0], [1,0]]) # (1,-1)*(1,3) + (2,-2)*(7,2) + (3,-3)*(5,11)
sess.run((d1,d2,d3,d4))

(-38, -38, -17, -10)

In [30]:
d2 = tf.tensordot(a, b, axes=[[0,1], [0,1]]) 
sess.run(d2)

-38

In [31]:
a3 = tf.constant([[[1, 1], [2, 2]], [[3, 3], [4, 4]]]) # (i,j,k) = (2,2,2)
b3 = tf.constant([[[0, 0],
                   [10, 10]],                  
                  [[-1, -1],
                   [1000, 1000]]]) # (l,m,n) = (2,2,2)

In [34]:
d4 = tf.tensordot(a3, b3, axes=[[0], [2]]) # (j,k,l,m) = (2,2,2,2)
sess.run(d4)

array([[[[   0,   40],
         [  -4, 4000]],

        [[   0,   40],
         [  -4, 4000]]],


       [[[   0,   60],
         [  -6, 6000]],

        [[   0,   60],
         [  -6, 6000]]]], dtype=int32)